# Start multiple ec2 instances with instance-specific tags assigned to each
#
- hosts: localhost
  vars:
    ec2_instances:
      - name: "jenkins"
        image: "ami-194cdc76" # ec2-user 12.04
        tags: ['jenkins']
        group_id: 'sg-c61e13ac' # jenkins-slave_new
        ssh_user: "ec2-user"
      - name: "test"
        image: "ami-194cdc76" # ec2-user 12.04
        tags: ['test']
        ssh_user: "ec2-user"
        group_id: 'sg-c61e13ac' # jenkins-slave_new
      - name: "deploy"
        image: "ami-194cdc76" # ec2-user 12.04
        tags: ['deploy']
        ssh_user: "ec2-user"
        group_id: 'sg-c61e13ac' # jenkins-slave_new  
  tasks:
    - name: Launch Instance
      ec2:
        group_id: "{{ item.group_id }}"
        count: 1
        instance_type: 't2.micro'
        image: '{{ item.image }}'
        wait: true
        region: 'eu-central-1'
        #keypair: '{{ keypair }}'
        aws_access_key: AKIAIAOPGJX43656VI4A
        aws_secret_key: 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
        instance_tags: "{{ item.tags }}"
      register: ec2
      with_items: ec2_instances

    - name: Wait for SSH
      wait_for:
        host: "{{ item['instances'][0]['public_ip'] }}"
        port: 22
        delay: 10
        timeout: 320
        state: started
      with_items: ec2.results

    - name: Wait a little longer for centos
      pause: seconds=20    
       
    - name: Add hosts group temporary inventory group with pem path
      add_host:
        name: "{{ item.1.platform }} {{ ec2.results[item.0]['instances'][0]['public_ip'] }}"
        groups: dynamic_hosts
        ansible_ssh_host: "{{ ec2.results[item.0]['instances'][0]['public_ip'] }}"
        ansible_ssh_private_key_file: '{{ pem_path }}'
        ansible_ssh_user: "{{ item.1.ssh_user }}"
        ec2_vars: "{{ ec2.results[item.0]['instances'][0] }}"
        ec2_instance_ids: "{{ ec2.results[item.0]['instance_ids'] }}"
      with_indexed_items: ec2_instances

- hosts: dynamic_hosts
  tasks:
    - ping:
